apiVersion: v1
kind: Service
metadata:
  name: library-costarica-app-service
spec:
  selector:
    app: library-costarica-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort

